import { rooms } from "..";
import { leaveRoom } from "./leaveRoom";
import { randomWords } from "./randomWords";

const listWords = [
  "Aatrox",
  "Akali",
  "Aurelion Sol",
  "Ahri",
  "Alistar",
  "Amumu",
  "Anivia",
  "Annie",
  "Ashe",
  "Azir",
  "Bard",
  "Blitzcrank",
  "Brand",
  "Braum",
  "Camille",
  "Caitlyn",
  "Cassiopeia",
  "Cho Gath",
  "Corki",
  "Darius",
  "Dr. Mundo",
  "Diana",
  "Draven",
  "Ekko",
  "Elise",
  "Evelynn",
  "Ezreal",
  "Fiddlesticks",
  "Fiora",
  "Fizz",
  "Galio",
  "Gangplank",
  "Garen",
  "Gnar",
  "Gragas",
  "Graves",
  "Hecarim",
  "Heimerdinger",
  "Irelia",
  "Ivern",
  "Illaoi",
  "Janna",
  "Jarvan IV",
  "Jax",
  "Jayce",
  "Jhin",
  "Jinx",
  "Karma",
  "Kalista",
  "Karthus",
  "Kassadin",
  "Kai Sa",
  "Katarina",
  "Kayn",
  "Kayle",
  "Kennen",
  "Kha Zix",
  "Kog Maw",
  "Kled",
  "Kindred",
  "LeBlanc",
  "Lee Sin",
  "Leona",
  "Lucian",
  "Lissandra",
  "Lulu",
  "Lux",
  "Malphite",
  "Malzahar",
  "Maokai",
  "Master Yi",
  "Miss Fortune",
  "Mordekaiser",
  "Morgana",
  "Nami",
  "Nasus",
  "Nautilus",
  "Neeko",
  "Nidalee",
  "Nocturne",
  "Nunu and Willump",
  "Olaf",
  "Ornn",
  "Orianna",
  "Pantheon",
  "Poppy",
  "Pyke",
  "Quinn",
  "Rammus",
  "Rakan",
  "Rek Sai",
  "Renekton",
  "Rengar",
  "Riven",
  "Rumble",
  "Ryze",
  "Sejuani",
  "Shaco",
  "Shen",
  "Shyvana",
  "Singed",
  "Sion",
  "Sivir",
  "Skarner",
  "Sona",
  "Soraka",
  "Swain",
  "Syndra",
  "Sylas",
  "Talon",
  "Taliyah",
  "Taric",
  "Tahm Kench",
  "Thresh",
  "Teemo",
  "Tristana",
  "Trundle",
  "Tryndamere",
  "Twisted Fate",
  "Twitch",
  "Udyr",
  "Urgot",
  "Varus",
  "Vayne",
  "Veigar",
  "Vel Koz",
  "Vi",
  "Viktor",
  "Vladimir",
  "Volibear",
  "Warwick",
  "Wukong",
  "Xayah",
  "Xerath",
  "Xin Zhao",
  "Yasuo",
  "Yorick",
  "Zac",
  "Zed",
  "Ziggs",
  "Zilean",
  "Zoe",
  "Zyra",
  "Yuumi",
  "Tibbers",
  "Senna",
  "Qiyana",
  "Sett",
  "Aphelios",
  "Lillia",
  "Yone",
  "Samira",
  "Seraphine",
  "Goku",
  "Vegeta",
  "Tenshinhan",
  "Chaos",
  "Trunks",
  "Gotenks",
  "Goten",
  "Pan",
  "Gohan",
  "Majin Buu",
  "Mr. Satan",
  "Jiren",
  "Hit",
  "Bulma",
  "Milk",
  "Whis",
  "Bills",
  "Freezer",
  "Cooler",
  "Raditz",
  "Bardock",
  "Yamcha",
  "Krillin",
  "Androide 18",
  "Androide 17",
  "Androide 16",
  "Androide 19",
  "Dr. Gero",
  "Cell",
  "Cell junior",
  "Patrulla Roja",
  "Gine",
  "Tao Pai Pai",
  "Maestro Roshi",
  "Trunks del Futuro",
  "Mr. Popo",
  "Babidi",
  "Dende",
  "Piccolo",
  "Shenlong",
  "Kaiosama",
  "Nappa",
  "Ginyu",
  "Yajirobe",
  "Karin",
  "Comandante Red",
  "Baby",
  "Pilaf",
  "Videl",
  "Maron",
  "Broly",
  "Dodoria",
  "Sarbon",
  "Garlic",
  "Janemba",
  "Gogeta",
  "Tapion",
  "Vegito",
  "Polunga",
  "Androide 8",
  "Uub",
  "Kale",
  "Caulifla",
  "Kefla",
  "Rey Vegeta",
  "Puar",
  "Supremo Kaiosama",
  "Uranai Baba",
  "Hildegarn",
  "Zenosama",
  "Genkidama",
  "Kamehameha",
  "Makankosappo",
  "Enma Daio Sama",
  "King Cold",
  "Kienzan",
  "Kaio Ken",
  "Dodonpa",
  "Janemba",
  "Arale",
  "Burter",
  "Recoome",
  "Gurdo",
  "Jeice",
  "uwu",
  "Ozaru",
  "Dabura",
  "Habitacion del Tiempo",
  "Corporacion Capsula",
  "Naruto",
  "Sasuke",
  "Gaara",
  "Itachi",
  "Sakura",
  "Kakashi",
  "Ino",
  "Hinata",
  "Jiraiya",
  "Minato",
  "Kushina",
  "Rock Lee",
  "Shikamaru",
  "Maito Gai",
  "Ten Ten",
  "Madara",
  "Neji",
  "Akamaru",
  "Kiba",
  "Choji",
  "Azuma",
  "Kurenai",
  "Orochimaru",
  "Tsunade",
  "Temari",
  "Kankuro",
  "Chijo",
  "Zabuza",
  "Kurama",
  "Haku",
  "Akatsuki",
  "Obito",
  "Kisame",
  "Deidara",
  "Pain",
  "Karin",
  "Konan",
  "Hidan",
  "Sasori",
  "Kakuzu",
  "Hashirama",
  "Zetsu Blanco",
  "Zetsu Negro",
  "Rasengan",
  "Chidori",
  "Sharingan",
  "Nagato",
  "Yahiko",
  "Hagoromo",
  "Shizune",
  "Anko",
  "Gandalf",
  "Aaragorn",
  "Gimli",
  "Legolas",
  "Frodo",
  "Sam",
  "Sauron",
  "Saruman",
  "Smeagol",
  "Gollum",
  "Boromir",
  "Harry Potter",
  "Hermione Granger",
  "Ron Weasley",
  "Voldemort",
  "Tom Riddle",
  "Albus Dumbledore",
  "Sirius Black",
  "Severus Snape",
  "Luna Lovegood",
  "Hagrid",
  "Draco Malfoy",
  "Dobby",
  "Neville Longbottom",
  "Quiddich",
  "Snitch Dorada",
  "Hedwig",
  "Ginny Weasley",
  "Griffindor",
  "Hufflepuff",
  "Slitherin",
  "Ravenclaw",
  "Dolores Umbridge",
  "Bellatrix Lestrange",
  "Nimbus 2000",
  "Nagini",
  "Dementores",
  "Luffy",
  "Soro",
  "Nami",
  "Batman",
  "Robin",
  "Guason",
  "Nico Robin",
  "Monet",
  "Light Yagami",
  "L",
  "Kira",
  "Levi",
  "Superman",
  "Hulk",
  "Iron man",
  "Thor",
  "Black Widow",
  "Hawkeye",
  "Loki",
  "Odin",
  "Capitan America",
  "Capitana Marvel",
  "Spiderman",
  "Antman",
  "Doctor Strange",
  "Thanos",
  "Groot",
  "Pantera Negra",
  "Rocket",
  "Gamura",
  "Starlord",
  "Drax",
  "Yondu",
  "Scarlet Witch",
  "Wolverine",
  "Quicksilver",
  "Magneto",
  "Profesor X",
  "Deadpool",
  "Flash",
  "Aquaman",
  "Mujer Maravilla",
  "Gatubela",
  "Anakin Skywalker",
  "Mace Windu",
  "Yoda",
  "Darth Vader",
  "Luke Skywalker",
  "Obi Wan Kenobi",
  "Flash",
  "Storm",
  "Ciclope",
  "Will Smith",
  "Harley Quinn",
  "Deadshot",
  "Bulbasaur",
  "Ivysaur",
  "Venusaur",
  "Charmander",
  "Charmeleon",
  "Charizard",
  "Squirtle",
  "Wartortle",
  "Blastoise",
  "Caterpie",
  "Metapod",
  "Butterfree",
  "Weedle",
  "Kakuna",
  "Beedrill",
  "Pidgey",
  "Pidgeotto",
  "Pidgeot",
  "Rattata",
  "Raticate",
  "Spearow",
  "Fearow",
  "Ekans",
  "Arbok",
  "Pikachu",
  "Raichu",
  "Sandshrew",
  "Sandslash",
  "Nidoran",
  "Nidorina",
  "Nidoqueen",
  "Nidorino",
  "Nidoking",
  "Clefairy",
  "Clefable",
  "Vulpix",
  "Ninetales",
  "Jigglypuff",
  "Wigglytuff",
  "Zubat",
  "Golbat",
  "Oddish",
  "Gloom",
  "Vileplume",
  "Paras",
  "Parasect",
  "Venonat",
  "Venomoth",
  "Diglett",
  "Dugtrio",
  "Meowth",
  "Persian",
  "Psyduck",
  "Golduck",
  "Mankey",
  "Primeape",
  "Growlithe",
  "Arcanine",
  "Poliwag",
  "Poliwhirl",
  "Poliwrath",
  "Abra",
  "Kadabra",
  "Alakazam",
  "Machop",
  "Machoke",
  "Machamp",
  "Bellsprout",
  "Weepinbell",
  "Victreebel",
  "Tentacool",
  "Tentacruel",
  "Geodude",
  "Graveler",
  "Golem",
  "Ponyta",
  "Rapidash",
  "Slowpoke",
  "Slowbro",
  "Magnemite",
  "Magneton",
  "Farfetch'd",
  "Doduo",
  "Dodrio",
  "Seel",
  "Dewgong",
  "Grimer",
  "Muk",
  "Shellder",
  "Cloyster",
  "Gastly",
  "Haunter",
  "Gengar",
  "Onix",
  "Drowzee",
  "Hypno",
  "Krabby",
  "Kingler",
  "Voltorb",
  "Electrode",
  "Exeggcute",
  "Exeggutor",
  "Cubone",
  "Marowak",
  "Hitmonlee",
  "Hitmonchan",
  "Lickitung",
  "Koffing",
  "Weezing",
  "Rhyhorn",
  "Rhydon",
  "Chansey",
  "Tangela",
  "Kangaskhan",
  "Horsea",
  "Seadra",
  "Goldeen",
  "Seaking",
  "Staryu",
  "Starmie",
  "Mr. Mime",
  "Scyther",
  "Jynx",
  "Electabuzz",
  "Magmar",
  "Pinsir",
  "Tauros",
  "Magikarp",
  "Gyarados",
  "Lapras",
  "Ditto",
  "Eevee",
  "Vaporeon",
  "Jolteon",
  "Flareon",
  "Porygon",
  "Omanyte",
  "Omastar",
  "Kabuto",
  "Kabutops",
  "Aerodactyl",
  "Snorlax",
  "Articuno",
  "Zapdos",
  "Moltres",
  "Dratini",
  "Dragonair",
  "Dragonite",
  "Mewtwo",
  "Mew",
  "Miguelangelo",
  "Donatello",
  "Maestro Splinter",
  "Rafaelo",
  "Leonardo",
  "Guido Kaczka",
  "Marley",
  "Sebastian Estevanez",
  "Seiya",
  "Ikki",
  "Hyoga",
  "Shun",
  "Shiryu",
  "Saori",
  "Yugi Muto",
  "Seto Kaiba",
  "Ash",
  "Brook",
  "Misty",
  "Profesor Oak",
  "Gary",
  "Tai",
  "Mat",
  "Kari",
  "TK",
  "Sora",
  "Mimi",
  "Izzy",
  "Joe",
  "Agumon",
  "Greymon",
  "Metalgreymon",
  "Angemon",
  "Patamon",
  "MagnaAngemon",
  "Gatomon",
  "Salomon",
  "Tentomon",
  "Palmon",
  "Togemon",
  "Lillymon",
  "Biyomon",
  "Gabumon",
  "Gomamon",
  "Garurumon",
  "Birdramon",
  "Garudamon",
  "Kabuterimon",
  "MegaKabuterimon",
  "Angewomon",
  "Ikkakumon",
  "Zudomon",
  "Weregarurumon",
  "Leomon",
  "Ogremon",
  "Shrek",
  "Burro",
  "Gato con Botas",
  "Fiona",
  "Pinocho",
  "Elsa",
  "Aladdin",
  "Genio de la Lampara",
  "Woody",
  "Buzz Lightyear",
  "Rex",
  "Rapunzel",
  "Mulan",
  "Blancanieves",
  "Bella Durmiente",
  "Cenicienta",
  "La Sirenita",
  "Bella",
  "Pocahontas",
  "Bob Esponja",
  "Calamardo",
  "Patricio Estrella",
  "Ricardo Fort",
  "Arenita",
  "Bombon",
  "Burbuja",
  "Bellota",
  "Mojo Jojo",
  "Profesor Utonio",
  "Alcalde de Saltadilla",
  "Jake Long",
  "Hamtaro",
  "Don Gato",
  "Homero",
  "Lisa",
  "Bart",
  "Marge",
  "Maggie",
  "Milhouse",
  "Gregory",
  "Burns",
  "Barney",
  "Smithers",
  "Krusty",
  "Flanders",
  "Carl",
  "Lenny",
  "Moe",
  "Nelson",
  "Willie",
  "Bob Patiño",
  "Apu Nahasapeemapetilon",
  "Skinner",
  "Troy McClure",
  "Kent Brockman",
  "Duffman",
  "Venom",
  "Capitan Jack Sparrow",
  "Alicia",
  "Sombrerero Loco",
  "Conejo Blanco",
  "Caperucita Roja",
  "Kirito",
  "Eren",
  "Mikasa",
  "Sailor Moon",
  "Garfield",
  "Odie",
  "Mafalda",
  "Sub Zero",
  "Scorpion",
  "Kano",
  "Liu Kang",
  "Goro",
  "Raiden",
  "Kitana",
  "Milena",
  "Jade",
  "Noob Saibot",
  "Johnny Cage",
  "Smoke",
  "Kung Lao",
  "Shang Tsung",
  "Sonya",
  "Shao Khan",
  "Rocket League",
  "Minecraft",
  "Ana",
  "Bastion",
  "D.va",
  "Doomfist",
  "Genji",
  "Hanzo",
  "Junkrat",
  "Lucio",
  "Mccree",
  "Mei",
  "Mercy",
  "Pharah",
  "Reaper",
  "Reinhardt",
  "Roadhog",
  "Soldier 76",
  "Sombra",
  "Symmetra",
  "Torbjorn",
  "Tracer",
  "Widowmaker",
  "Winston",
  "Zarya",
  "Zenyatta",
  "Sonic",
  "Tails",
  "Knuckles",
  "Aang",
  "Katara",
  "Toph",
  "Suko",
  "Soka",
  "Azula",
  "Iroh",
  "Appa",
  "Jessie",
  "James",
  "Equipo Rocket,",
];

export const joinRoom = (roomId, user, socket) => {
  const userInRoom = rooms[roomId].participants.filter(
    (room) => room.userId === user.userId
  );
  const room = rooms[roomId];
  const roomParticipants = rooms[roomId].participants;
  if (room && userInRoom.length === 0) {
    if (roomParticipants.length === 0) {
      roomParticipants.push({
        ...user,
        isOwner: true,
        wordRoundZero: randomWords(listWords),
        wordRoundOne: randomWords(listWords),
      });
    } else {
      roomParticipants.push({
        ...user,
        wordRoundZero: randomWords(listWords),
        wordRoundOne: randomWords(listWords),
      });
    }

    socket.join(roomId);
    socket.emit("get-users", {
      roomId: roomId,
      participants: roomParticipants,
    });
    socket.to(roomId).emit("user-joined", { user });
    console.log(`user joined the room: ${roomId} - ${user.userId}`);
  }

  socket.on("disconnect", () => {
    console.log("user left the room", user.userId);
    leaveRoom(roomId, user, socket);
  });
};
